### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by poma** [tornadocash/trusted-ui#1]
# General

- [ ] compute results and radix files for PPoT ceremony
- [ ] test concurrent contributions
- [ ] add dockerfile for Rust phase2
- [ ] add DB for contribution metadata
- [ ] twitter and github OAuth
- [ ] ability to add contribution metadata after contribution from source
- [ ] test S3 uploads
- [ ] test scripts that verify contributions and generate prover/verifier keys and verifier contract with real Tornado data and UI

# UI

- [ ] design web UI
...

# Audit of contribution generation code

# Post ceremony

- [ ] generate final keys
- [ ] upload ceremony transcript to IPFS
- [ ] make a medium post with results

**Comment by ytrezq** [comment]
@poma : add an option for manually computing proof from the webassembly module ?

**Comment by poma** [comment]
No. You should compile from Rust source code instead and use CLI (there is also a Docker version)

**Comment by ytrezq** [comment]
@poma : but then, where’s the source code ?

**Comment by poma** [comment]
https://github.com/tornadocash/phase2-bn254/tree/ceremony

**Comment by ytrezq** [comment]
@poma : given a note, along a root and a nullifier, and other withdrawal parameters, I want to compute the proof using the proving keys deployed on the Ethereum mainnet.

I don’t see any ᴄʟɪ program for that.

**Comment by poma** [comment]
oh you mean proof and not contribution. In this case you are asking this in a wrong repo. This repository is about Trusted Setup MPC ceremony

**Comment by ytrezq** [comment]
@poma : isn’t this repo about the [source code of the website](https://tornado.cash/) ?

**Comment by poma** [comment]
no, this is only for trusted setup

**Comment by ytrezq** [comment]
@poma : so what’s the right place ?

**Comment by poma** [comment]
https://github.com/tornadocash/tornado-core

you will also find cli.js tool there

**Comment by ytrezq** [comment]
@poma : the point is testing proof generation for deposits that didn’t occur on any networks.
How I can do that ? And use the mainnet’s proving keys ?

**Comment by ytrezq** [comment]
@poma : how to use it in browser ?
